/* Generated By:JavaCC: Do not edit this line. RobotParserConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int T_MOVE = 6;
  /** RegularExpression Id. */
  int T_TURNRIGHT = 7;
  /** RegularExpression Id. */
  int T_PUTB = 8;
  /** RegularExpression Id. */
  int T_PICKB = 9;
  /** RegularExpression Id. */
  int T_PUTC = 10;
  /** RegularExpression Id. */
  int T_PICKC = 11;
  /** RegularExpression Id. */
  int T_ASSIGN = 12;
  /** RegularExpression Id. */
  int T_TURN = 13;
  /** RegularExpression Id. */
  int T_FACE = 14;
  /** RegularExpression Id. */
  int T_PUT = 15;
  /** RegularExpression Id. */
  int T_PICK = 16;
  /** RegularExpression Id. */
  int T_MOVEDIR = 17;
  /** RegularExpression Id. */
  int T_SKIP = 18;
  /** RegularExpression Id. */
  int T_MOVE1 = 19;
  /** RegularExpression Id. */
  int T_FACING = 20;
  /** RegularExpression Id. */
  int T_CANPUT = 21;
  /** RegularExpression Id. */
  int T_CANPICK = 22;
  /** RegularExpression Id. */
  int T_CANMOVE = 23;
  /** RegularExpression Id. */
  int T_NOT = 24;
  /** RegularExpression Id. */
  int T_IF = 25;
  /** RegularExpression Id. */
  int T_WHILE = 26;
  /** RegularExpression Id. */
  int T_REPEAT = 27;
  /** RegularExpression Id. */
  int VARS = 28;
  /** RegularExpression Id. */
  int T_BEGIN = 29;
  /** RegularExpression Id. */
  int T_END = 30;
  /** RegularExpression Id. */
  int PI = 31;
  /** RegularExpression Id. */
  int PD = 32;
  /** RegularExpression Id. */
  int COMA = 33;
  /** RegularExpression Id. */
  int SC = 34;
  /** RegularExpression Id. */
  int DIRECTION = 35;
  /** RegularExpression Id. */
  int FACE = 36;
  /** RegularExpression Id. */
  int NUM = 37;
  /** RegularExpression Id. */
  int VAR = 38;
  /** RegularExpression Id. */
  int XT = 39;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\\n\"",
    "\"Move\"",
    "\"TURNRIGHT\"",
    "\"PutB\"",
    "\"PickB\"",
    "\"PutC\"",
    "\"PickC\"",
    "\"Assign\"",
    "\"Turn\"",
    "\"Face\"",
    "\"Put\"",
    "\"Pick\"",
    "\"MoveDir\"",
    "\"Skip\"",
    "\"Move(\"",
    "\"facing\"",
    "\"canPut\"",
    "\"canPick\"",
    "\"canMove\"",
    "\"not\"",
    "\"if\"",
    "\"while\"",
    "\"Repeat\"",
    "\"VARS\"",
    "\"BEGIN\"",
    "\"END\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\";\"",
    "<DIRECTION>",
    "<FACE>",
    "<NUM>",
    "<VAR>",
    "<XT>",
    "\"ROBOT_R\"",
  };

}
